### PR TITLE
Zwischenstand

### PR DESCRIPTION
**Pull request by mschop**
A collection oft many changes

### CODE REVIEW

**Comment by dbogatz** [comment]
Mahlzeit!

Sorry für die späte Rückmeldung aber es schien als ob Du das alles im Griff hattest und ich hatte noch einige private Verpflichtungen.
Ich hatte jetzt auch noch keine Zeit den neuen Stand zu Testen – jetzt wo die Schulferien zuende sind, sind meine Kinder hoffentlich “erschöpfter” und gönnen mir mehr Ruhe 
Die Admins/Mods warten schon auf Verbesserungen.

Gruß

Denys.


From: mschop 
Sent: Wednesday, November 25, 2015 9:29 PM
To: dbogatz/node-galaxyboard 
Subject: [node-galaxyboard] Zwischenstand (#5)

Hallo Denys,

kannst du die bisherigen Änderungen einmal in dein Repo übernehmen? Da es sich bei meinem Repo um einen Fork handelt, werden meine Änderungen nicht als Contributions gezählt. Da die Contributions bei Bewerbungen usw. als Aushängeschild dienen, bin ich natürlich daran interessiert, dass diese in der Statistik eingehen.

Danke im Voraus.

Gruß
Martin


--------------------------------------------------------------------------------

You can view, comment on, or merge this pull request online at:
  https://github.com/dbogatz/node-galaxyboard/pull/5

Commit Summary
  a.. basic setup 
  b.. added testing & travis stuff 
  c.. test automatic deployment 
  d.. fixed intendation in .travis.yml 
  e.. fixed password# 
  f.. prepared for cloudControl 
  g.. fixed for cloudControl deployment 
  h.. removed error mail 
  i.. fixed port problem 
  j.. nothing done 
  k.. added asset debugging 
  l.. optimized build process & added asset compilation 
  m.. tryfix deployment pipeline 
  n.. catch exceptions in before_deploy.js 
  o.. default connection limit 
  p.. deploy test 
  q.. deploy test 
  r.. deploy test 
  s.. deploy test 
  t.. deploy test 
  u.. deploy test 
  v.. deploy test 
  w.. deploy test 
  x.. deploy test 
  y.. deploy test 
  z.. deploy test 
  aa.. changes ccpass 
  ab.. deploy test 
  ac.. deploy test 
  ad.. deploy test 
  ae.. deploy test 
  af.. deploy test 
  ag.. deploy test 
  ah.. deploy test 
  ai.. deploy test 
  aj.. deploy test 
  ak.. deploy test 
  al.. deploy test 
  am.. deploy test 
  an.. deploy test 
  ao.. deploy test 
  ap.. deploy test 
  aq.. deploy test 
  ar.. deploy test 
  as.. deploy test 
  at.. deploy test 
  au.. deploy test 
  av.. deploy test 
  aw.. deploy test 
  ax.. no cloud control - prepare for normal vServers 
  ay.. removed unnecessary file 
  az.. added deployment known host 
  ba.. added deployment known host 
  bb.. added deployment known host 
  bc.. added deployment known host 
  bd.. added deployment known host 
  be.. added deployment known host 
  bf.. added deployment known host 
  bg.. fixed up.sh error 
  bh.. fixed autodeploy 
  bi.. fixed installation 
  bj.. changed deployment provider 
  bk.. changed deployment provider 
  bl.. changed deployment provider 
  bm.. changed deployment provider 
  bn.. changed deployment provider 
  bo.. changed deployment provider 
  bp.. changed deployment provider 
  bq.. changed deployment provider 
  br.. changed deployment provider 
  bs.. changed deployment provider 
  bt.. changed deployment provider 
  bu.. changed deployment provider 
  bv.. finalized deployment scripts 
  bw.. Merge branch 'feature/crudBoard' 
  bx.. added board insert functions 
  by.. changed migration & up/down scripts 
  bz.. fix middlewares & formatting 
  ca.. added entities & basic tests 
  cb.. Merge branch 'master' of github.com:mschop/node-galaxyboard into boardCrud 
  cc.. Merge remote-tracking branch 'upstream/master' into upstream 
  cd.. migration to inndb & first connectApi design & implementation 
  ce.. Merge branch 'master' of github.com:mschop/node-galaxyboard 
  cf.. migration to innodb 
  cg.. removed useless exception wrapping for better debugging purposes 
  ch.. removed debug() function 
  ci.. removed last debug() usages 
  cj.. bugfix template engine 
  ck.. fixed breadcrum generation 
  cl.. restructured admin menu 
  cm.. bugfix cannot add topic 
  cn.. admin options styling 
  co.. bugfix show buttons only if in thread 
  cp.. styled topic moderation menu 
  cq.. basic board add popup 
  cr.. changed flag structure 
  cs.. fixed search mouse over 
  ct.. introduced jquery 
  cu.. bugfix post not viewable for user 
  cv.. fixed post reply message empty 
  cw.. removed all in template accesses and moved many click events to js file 
  cx.. fixed deleting topic by using flag instead of deleting the rows 
  cy.. fixed creating topic naming issue 
  cz.. fixed missing create topic button for super admin 
  da.. hide second topic button if only a few topics 
  db.. bugfix adding topic not increasing topiccount for board 
  dc.. data correction for topiccount 
  dd.. fixed topic list not updated after topic deletion 
  de.. introducing bower and grunt 
File Changes
  a.. M .gitignore (6) 
  b.. A .travis.yml (10) 
  c.. A Gruntfile.js (16) 
  d.. A LICENCE (23) 
  e.. M README.md (30) 
  f.. M board.js (96) 
  g.. D board.sql (0) 
  h.. A bower.json (24) 
  i.. D config/default.json (13) 
  j.. A connect_api/index.js (39) 
  k.. D database.json (18) 
  l.. A deploy.sh (10) 
  m.. A docs/config_example.json (27) 
  n.. A galaxyboard.enc (0) 
  o.. A galaxyboard/ErrorHandling.js (42) 
  p.. A galaxyboard/Flags.js (123) 
  q.. D galaxyboard/GBFlags.js (146) 
  r.. A galaxyboard/GroupACL.js (25) 
  s.. A galaxyboard/InjectPromise.js (8) 
  t.. A galaxyboard/UserACL.js (19) 
  u.. A galaxyboard/database_service/acl.js (41) 
  v.. A galaxyboard/database_service/index.js (3) 
  w.. A galaxyboard/entities/Board.js (15) 
  x.. A galaxyboard/entities/index.js (1) 
  y.. M galaxyboard/index.js (1761) 
  z.. A galaxyboard/tools/collection.js (22) 
  aa.. A galaxyboard/tools/index.js (15) 
  ab.. A galaxyboard/tools/object.js (19) 
  ac.. A galaxyboard/tools/variable.js (8) 
  ad.. M htdocs/index.html (5) 
  ae.. M htdocs/static/CTemplate.js (2) 
  af.. M htdocs/static/Framework.js (1796) 
  ag.. A htdocs/static/connected_api_documentation/swagger-ui/css/print.css (1172) 
  ah.. A htdocs/static/connected_api_documentation/swagger-ui/css/reset.css (125) 
  ai.. A htdocs/static/connected_api_documentation/swagger-ui/css/screen.css (1279) 
  aj.. A htdocs/static/connected_api_documentation/swagger-ui/css/style.css (250) 
  ak.. A htdocs/static/connected_api_documentation/swagger-ui/css/typography.css (26) 
  al.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-700.eot (0) 
  am.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-700.svg (411) 
  an.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-700.ttf (0) 
  ao.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-700.woff (0) 
  ap.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-700.woff2 (0) 
  aq.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-regular.eot (0) 
  ar.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-regular.svg (403) 
  as.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-regular.ttf (0) 
  at.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-regular.woff (0) 
  au.. A htdocs/static/connected_api_documentation/swagger-ui/fonts/droid-sans-v6-latin-regular.woff2 (0) 
  av.. A htdocs/static/connected_api_documentation/swagger-ui/images/explorer_icons.png (0) 
  aw.. A htdocs/static/connected_api_documentation/swagger-ui/images/favicon-16x16.png (0) 
  ax.. A htdocs/static/connected_api_documentation/swagger-ui/images/favicon-32x32.png (0) 
  ay.. A htdocs/static/connected_api_documentation/swagger-ui/images/favicon.ico (0) 
  az.. A htdocs/static/connected_api_documentation/swagger-ui/images/logo_small.png (0) 
  ba.. A htdocs/static/connected_api_documentation/swagger-ui/images/pet_store_api.png (0) 
  bb.. A htdocs/static/connected_api_documentation/swagger-ui/images/throbber.gif (0) 
  bc.. A htdocs/static/connected_api_documentation/swagger-ui/images/wordnik_api.png (0) 
  bd.. A htdocs/static/connected_api_documentation/swagger-ui/index.html (119) 
  be.. A htdocs/static/connected_api_documentation/swagger-ui/lang/en.js (53) 
  bf.. A htdocs/static/connected_api_documentation/swagger-ui/lang/es.js (52) 
  bg.. A htdocs/static/connected_api_documentation/swagger-ui/lang/pt.js (53) 
  bh.. A htdocs/static/connected_api_documentation/swagger-ui/lang/ru.js (52) 
  bi.. A htdocs/static/connected_api_documentation/swagger-ui/lang/translator.js (39) 
  bj.. A htdocs/static/connected_api_documentation/swagger-ui/lib/backbone-min.js (15) 
  bk.. A htdocs/static/connected_api_documentation/swagger-ui/lib/handlebars-2.0.0.js (28) 
  bl.. A htdocs/static/connected_api_documentation/swagger-ui/lib/highlight.7.3.pack.js (1) 
  bm.. A htdocs/static/connected_api_documentation/swagger-ui/lib/jquery-1.8.0.min.js (2) 
  bn.. A htdocs/static/connected_api_documentation/swagger-ui/lib/jquery.ba-bbq.min.js (18) 
  bo.. A htdocs/static/connected_api_documentation/swagger-ui/lib/jquery.slideto.min.js (1) 
  bp.. A htdocs/static/connected_api_documentation/swagger-ui/lib/jquery.wiggle.min.js (8) 
  bq.. A htdocs/static/connected_api_documentation/swagger-ui/lib/marked.js (1272) 
  br.. A htdocs/static/connected_api_documentation/swagger-ui/lib/swagger-oauth.js (290) 
  bs.. A htdocs/static/connected_api_documentation/swagger-ui/lib/underscore-min.js (6) 
  bt.. A htdocs/static/connected_api_documentation/swagger-ui/lib/underscore-min.map (1) 
  bu.. A htdocs/static/connected_api_documentation/swagger-ui/o2c.html (20) 
  bv.. A htdocs/static/connected_api_documentation/swagger-ui/swagger-ui.js (32183) 
  bw.. A htdocs/static/connected_api_documentation/swagger-ui/swagger-ui.min.js (13) 
  bx.. A htdocs/static/connected_api_documentation/swagger.yaml (154) 
  by.. R htdocs/static/gfx/header-gfx_backup.jpg (0) 
  bz.. R htdocs/static/gfx/header-gfx_backup.png (0) 
  ca.. M htdocs/static/lang-de.js (266) 
  cb.. A htdocs/static/libs/font-awesome-4.4.0/HELP-US-OUT.txt (7) 
  cc.. A htdocs/static/libs/font-awesome-4.4.0/css/font-awesome.css (2026) 
  cd.. A htdocs/static/libs/font-awesome-4.4.0/css/font-awesome.min.css (4) 
  ce.. A htdocs/static/libs/font-awesome-4.4.0/fonts/FontAwesome.otf (0) 
  cf.. A htdocs/static/libs/font-awesome-4.4.0/fonts/fontawesome-webfont.eot (0) 
  cg.. A htdocs/static/libs/font-awesome-4.4.0/fonts/fontawesome-webfont.svg (640) 
  ch.. A htdocs/static/libs/font-awesome-4.4.0/fonts/fontawesome-webfont.ttf (0) 
  ci.. A htdocs/static/libs/font-awesome-4.4.0/fonts/fontawesome-webfont.woff (0) 
  cj.. A htdocs/static/libs/font-awesome-4.4.0/fonts/fontawesome-webfont.woff2 (0) 
  ck.. A htdocs/static/libs/font-awesome-4.4.0/less/animated.less (34) 
  cl.. A htdocs/static/libs/font-awesome-4.4.0/less/bordered-pulled.less (25) 
  cm.. A htdocs/static/libs/font-awesome-4.4.0/less/core.less (12) 
  cn.. A htdocs/static/libs/font-awesome-4.4.0/less/fixed-width.less (6) 
  co.. A htdocs/static/libs/font-awesome-4.4.0/less/font-awesome.less (17) 
  cp.. A htdocs/static/libs/font-awesome-4.4.0/less/icons.less (677) 
  cq.. A htdocs/static/libs/font-awesome-4.4.0/less/larger.less (13) 
  cr.. A htdocs/static/libs/font-awesome-4.4.0/less/list.less (19) 
  cs.. A htdocs/static/libs/font-awesome-4.4.0/less/mixins.less (26) 
  ct.. A htdocs/static/libs/font-awesome-4.4.0/less/path.less (15) 
  cu.. A htdocs/static/libs/font-awesome-4.4.0/less/rotated-flipped.less (20) 
  cv.. A htdocs/static/libs/font-awesome-4.4.0/less/stacked.less (20) 
  cw.. A htdocs/static/libs/font-awesome-4.4.0/less/variables.less (688) 
  cx.. A htdocs/static/libs/font-awesome-4.4.0/scss/_animated.scss (34) 
  cy.. A htdocs/static/libs/font-awesome-4.4.0/scss/_bordered-pulled.scss (25) 
  cz.. A htdocs/static/libs/font-awesome-4.4.0/scss/_core.scss (12) 
  da.. A htdocs/static/libs/font-awesome-4.4.0/scss/_fixed-width.scss (6) 
  db.. A htdocs/static/libs/font-awesome-4.4.0/scss/_icons.scss (677) 
  dc.. A htdocs/static/libs/font-awesome-4.4.0/scss/_larger.scss (13) 
  dd.. A htdocs/static/libs/font-awesome-4.4.0/scss/_list.scss (19) 
  de.. A htdocs/static/libs/font-awesome-4.4.0/scss/_mixins.scss (26) 
  df.. A htdocs/static/libs/font-awesome-4.4.0/scss/_path.scss (15) 
  dg.. A htdocs/static/libs/font-awesome-4.4.0/scss/_rotated-flipped.scss (20) 
  dh.. A htdocs/static/libs/font-awesome-4.4.0/scss/_stacked.scss (20) 
  di.. A htdocs/static/libs/font-awesome-4.4.0/scss/_variables.scss (0) 
  dj.. A htdocs/static/libs/font-awesome-4.4.0/scss/font-awesome.scss (0) 
  dk.. A htdocs/static/style.css (0) 
  dl.. D htdocs/static/style.scss (0) 
  dm.. I htdocs/templates.html (0) 
  dn.. A install/install.sh (0) 
  do.. A install/prepare_migration.js (0) 
  dp.. A integration_tests/all.js (0) 
  dq.. A integration_tests/test_board_crud.js (0) 
  dr.. A known_hosts (0) 
  ds.. A migrations/20150722211828-init.js (0) 
  dt.. A migrations/20150830192820-innodb.js (0) 
  du.. A migrations/20150831192820-connectApi.js (0) 
  dv.. A migrations/20151117204459-TopicDeletionByFlag.js (0) 
  dw.. A migrations/20151121101213-recountTopics.js (0) 
  dx.. A migrations/sqls/20150722211828-init-down.sql (0) 
  dy.. A migrations/sqls/20150722211828-init-up.sql (0) 
  dz.. A migrations/sqls/20150830192820-innodb-down.sql (0) 
  ea.. A migrations/sqls/20150830192820-innodb-up.sql (0) 
  eb.. A migrations/sqls/20150831192820-connectApi-down.sql (0) 
  ec.. A migrations/sqls/20150831192820-connectApi-up.sql (0) 
  ed.. A migrations/sqls/20151117204459-TopicDeletionByFlag-down.sql (0) 
  ee.. A migrations/sqls/20151117204459-TopicDeletionByFlag-up.sql (0) 
  ef.. A migrations/sqls/20151121101213-recountTopics-up.sql (0) 
  eg.. I package.json (0) 
  eh.. A unit_tests/GroupACL.js (0) 
  ei.. A unit_tests/UserACL.js (0) 
  ej.. A unit_tests/all.js (0) 
  ek.. A unit_tests/entities/Board.js (0) 
  el.. A unit_tests/entities/index.js (0) 
  em.. A unit_tests/tools/collection.js (0) 
  en.. A unit_tests/tools/index.js (0) 
  eo.. A unit_tests/tools/object.js (0) 
  ep.. A unit_tests/tools/variable.js (0) 
Patch Links:
  a.. https://github.com/dbogatz/node-galaxyboard/pull/5.patch 
  b.. https://github.com/dbogatz/node-galaxyboard/pull/5.diff

**Comment by mschop** [comment]
Hallo Denys,

bitte entschuldige, dass ich mich auch erst jetzt wieder melde. War in der
letzten Zeit sehr stressig bei mir und ich bin leider auch nicht so schnell
voran gekommen wie ich wollte. Der derzeitige Stand beinhaltet nur wenig
neue Features. Bis zum wirklichen Testen neuer Funktionalitäten werde ich
noch so 1-2 Monate brauchen. Ich hatte erstmal doch noch einige Änderungen
an der Architektur vorgenommen. Du kannst allerdings sehr gerne dir die
bisherigen Änderungen Code-Seitig anschauen und mir diesbezüglich Feedback
geben.

Gruß
Martin

**Comment by mschop** [comment]
Noch eine kleine Sache. Die Accounts, die in GT gelöscht werden, kann man
die wieder herstellen? Ich glaube ich habe mich zu lange nicht mehr in GT
eingeloggt, sodass mein Account gelöscht wurde xD

**Comment by dbogatz** [comment]
Aloha!

Bei mir ist das auch unverändert stressig – ich befürchte das ich erst als Rentner wieder mehr Zeit haben werde – zumindest wenn die Kinder mal aus dem Haus sind :/
Die wenige Zeit die mir im ganzen Trubel bleibt versuche ich nun sinnvoll mit etwas Sport/Ernährungsumstellung zu verbringen da ich diese Themen wohl zulang und zustark vernachlässigt habe. Nichtsdestotrotz hoffe ich mal dieses WE im Spiel voran zu kommen (Heldensystem).
Gelöschte Spielaccounts kann man über ein altes Backup wiederherstellen – ist natürlich mit etwas manuellem Aufwand verbunden.
Gruß
Denys.

**Pull request merged**
